theme: jekyll-theme-dinky
title: lar_testing
description: Multiple Testing and Variable Selection along Least Angle Regression path
show_downloads: true
google_analytics: UA-3278327-4
github:
  is_user_page: true
  is_project_page: true
  owner_url: https://ydecastro.github.io/
